apiVersion: v1
kind: Pod
metadata:
  name: test-pd-empty
spec: 
  containers:
    - name: test-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /empty
          name: cache-volume
  volumes:
      - name: cache-volume
        emptyDir: {}