apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec: 
  containers:
    - name: test-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /test-pd
          name: test-volume
  volumes:
      - name: test-volume
        hostPath:
          path: /data
          type: Directory
